# #
#   @type               github workflow
#   @author             Aetherinox
#   @url                https://github.com/Aetherinox
#   @usage              builds and releases binary files for ntfy-desktop
#                       creates a new github release
#
#   @secrets            secrets.SELF_TOKEN                                          self github personal access token (fine-grained)
#                       secrets.SELF_TOKEN_CL                                       self github personal access token (classic)
#                       secrets.NPM_TOKEN                                           self npmjs access token
#                       secrets.PYPI_API_TOKEN                                      self Pypi API token (production site) - https://pypi.org/
#                       secrets.PYPI_API_TEST_TOKEN                                 self Pypi API token (test site) - https://test.pypi.org/
#                       secrets.SELF_DOCKERHUB_TOKEN                                self Dockerhub token
#                       secrets.CODECOV_TOKEN                                       codecov upload token for nodejs projects
#                       secrets.MAXMIND_GELITE_TOKEN                                maxmind API token
#                       secrets.CF_ACCOUNT_ID                                       cloudflare account id
#                       secrets.CF_ACCOUNT_TOKEN                                    cloudflare account token
#                       secrets.ORG_TOKEN                                           org github personal access token (fine-grained)
#                       secrets.ORG_TOKEN_CL                                        org github personal access token (classic)
#                       secrets.ORG_DOCKERHUB_TOKEN                                 org dockerhub secret
#                       secrets.ORG_GITEA_TOKEN                                     org gitea personal access token (classic) with package:write permission
#                       secrets.BOT_GPG_KEY_ASC                                     bot gpg private key (armored) | BEGIN PGP PRIVATE KEY BLOCK
#                       secrets.BOT_GPG_KEY_B64                                     bot gpg private key (binary) converted to base64
#                       secrets.BOT_GPG_PASSPHRASE                                  bot gpg private key passphrase
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_RELEASES                discord webhook to report release notifications from github to discord
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_WORKFLOWS               discord webhook to report workflow notifications from github to discord
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_UPDATES                 discord webhook to report activity notifications from github to discord
#
#   @local              these workflows can be tested locally through the use of `act`
#                           https://github.com/nektos/act
#                       Extract act to folder
#                       Add system env var with path to act.exe
#                       Run the commands:
#                           git pull https://github.com/username/repo
#                           act -W .github/workflows/package-release.yml -P ubuntu-latest=catthehacker/ubuntu:full-22.04
#                           act -W .github/workflows/package-release.yml -s TOKEN_CL=XXXXXXXXXX --pull=false
# #

name: '📦 Package › Release'
run-name: '📦 Package › Release'

# #
#   triggers
# #

on:
    workflow_dispatch:
        inputs:

            # #
            #   Name of the plugin to use when creating the release zip filename
            #     e.g: ntfy-desktop-v1.0.0.zip
            # #

            PROJECT_NAME:
                description:          '📦 Name of App'
                required:             true
                default:              'ntfy-desktop'
                type:                 string

            # #
            #   ENABLE:   the changelog generated in releases tab will only display single commits.
            #   DISABLE:  the changelog shows pull requests completed based on their labels
            # #

            CHANGELOG_MODE_COMMIT:
                description:          '📑 Use Commits Instead of PRs'
                required:             true
                default:              true
                type:                 boolean

            # #
            #   ENABLE:   Will show all types of commits, including uncategorized
            #   DISABLE:  WIll only show actions that have been categorized using the format
            #                type(scope): description
            #                type: description
            # #

            SHOW_UNCATEGORIZED:
                description:          '🗂️ Show Uncategorized Commits'
                required:             true
                default:              false
                type:                 boolean

            # #
            #   true            released version will be marked as a development build and will have the v1.x.x-development tag instead of -latest
            #   false           release version will be marked with -latest docker tag
            # #

            RC_RELEASE:
                description:        '🧪 Release RC (Pre-release)'
                required:           true
                default:            false
                type:               boolean

            # #
            #   only needed if env variable `RC_RELEASE` = true
            #   sets the version number for the release candidate
            #       e.g: ntfy-desktop-v1.0.0-rc.1
            # #

            RC_VERSION:
                description:        '🧪 RC (Pre-release) Ver (ntfy-desktop-rc.1)'
                required:           false
                type:               string
                default:            '1'

# #
#   environment variables
# #

env:
    PROJECT_NAME:                   ${{ github.event.inputs.PROJECT_NAME || 'ntfy-desktop' }}
    CHANGELOG_MODE_COMMIT:          ${{ github.event.inputs.CHANGELOG_MODE_COMMIT || true }}
    SHOW_UNCATEGORIZED:             ${{ github.event.inputs.SHOW_UNCATEGORIZED || false }}
    RC_RELEASE:                     ${{ github.event.inputs.RC_RELEASE || false }}
    RC_VERSION:                     ${{ github.event.inputs.RC_VERSION || '1' }}
    ASSIGN_USER:                    Aetherinox

# #
#   Jobs
# #

jobs:

    # #
    #   JOB > INITIALIZE
    # #

    job-initialize:
        name: >-
            📦 Publish › Initialize
        runs-on: ubuntu-latest
      # runs-on: apollo-x64
        timeout-minutes: 5
        outputs:
            package_version: ${{ steps.task_initialize_package_getversion.outputs.PACKAGE_VERSION }}
        permissions:
            contents: write
            packages: write
        steps:

            # #
            #   Release › Checkout
            # #

            - name: '☑️ Checkout'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Initialize › Job Information
            # #

            - name: >-
                  🔄 Load Job
              uses: qoomon/actions--context@v4
              id: 'context'

            # #
            #   Initialize › Start
            # #

            - name: >-
                  ✅ Start
              run: |
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo " Starting Job ${{ steps.context.outputs.job_name }}"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"

                  year="$(date +'%Y')"
                  echo "YEAR=${year}" >> $GITHUB_ENV

                  now="$(date +'%m-%d-%Y %H:%M:%S')"
                  echo "NOW=${now}" >> $GITHUB_ENV

                  now_short="$(date +'%m-%d-%Y')"
                  echo "NOW_SHORT=${now_short}" >> $GITHUB_ENV

                  now_long="$(date +'%m-%d-%Y %H:%M')"
                  echo "NOW_LONG=${now_long}" >> $GITHUB_ENV

                  now_docker="$(date +'%Y%m%d')"
                  echo "NOW_DOCKER=${now_docker}" >> $GITHUB_ENV

                  now_docker_ts="$(date -u +'%FT%T.%3NZ')"
                  echo "NOW_DOCKER_TS=${now_docker}" >> $GITHUB_ENV

                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo -e
                  sudo apt -qq update
                  sudo apt -qq install tree
                  echo -e
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo -e
                  echo " Runner .............. ${{ runner.name }}"
                  echo " Workflow ............ ${{ github.workflow }} (#${{ github.workflow_ref }})"
                  echo " Run Number .......... #${{ github.run_number }}"
                  echo " Ref ................. #${{ github.ref }}"
                  echo " Ref Name ............ #${{ github.ref_name }}"
                  echo " Event Name .......... #${{ github.event_name }}"
                  echo " Repo ................ #${{ github.repository }}"
                  echo " Repo Owner .......... #${{ github.repository_owner }}"
                  echo " Run ID .............. https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  echo " Triggered By ........ ${{ github.actor }}"
                  echo " SHA 1 ............... ${GITHUB_SHA}"
                  echo " SHA 2 ............... ${{ github.sha }}"
                  echo " Workspace ........... ${{ github.workspace }}"
                  echo " PWD ................. ${PWD}"
                  echo " Job Name ............ ${{ steps.context.outputs.job_name }}"
                  echo " Job ID .............. ${{ steps.context.outputs.job_id }}"
                  echo " Job URL ............. ${{ steps.context.outputs.job_url }}"
                  echo " Run ID .............. ${{ steps.context.outputs.run_id }}"
                  echo " Run Attempt ......... ${{ steps.context.outputs.run_attempt }}"
                  echo " Run Number .......... ${{ steps.context.outputs.run_number }}"
                  echo " Run URL ............. ${{ steps.context.outputs.run_url }}"
                  echo " Run Env ............. ${{ steps.context.outputs.environment }}"
                  echo " Run Env URL ......... ${{ steps.context.outputs.environment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Deployment URL .. ${{ steps.context.outputs.deployment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Runner Name ..... ${{ steps.context.outputs.runner_name }}"
                  echo " Run Runner ID ....... ${{ steps.context.outputs.runner_id }}"
                  echo " Year ................ ${YEAR}"
                  echo " Now ................. ${NOW}"
                  echo " Now (Short) ......... ${NOW_SHORT}"
                  echo " Now (Long) .......... ${NOW_LONG}"
                  echo " Now (Docker) ........ ${NOW_DOCKER}"
                  echo " Now (Docker TS) ..... ${NOW_DOCKER_TS}"
                  echo -e
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo -e
                  tree -I node_modules -I .git
                  echo -e
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"

            # #
            #   Get version from package.json VERSION value
            # #

            - name: '👁️‍🗨️ Get Package Version'
              id: task_initialize_package_getversion
              working-directory: ./src
              run: |
                  VER=$(cat package.json | jq -r '.version')
                  echo "PACKAGE_VERSION=$VER" >> $GITHUB_OUTPUT

            - name: '👁️‍🗨️ Get Package Version › Print'
              run: |
                  echo "VERSION: ${{ steps.task_initialize_package_getversion.outputs.PACKAGE_VERSION }}"

    # #
    #   Job › Build › Windows
    # #

    job-build-windows:
        name: >-
            📦 Publish › Build › Windows
        needs: job-initialize
        runs-on: ubuntu-latest
      # runs-on: apollo-x64
        timeout-minutes: 5
        env:
            PACKAGE_VERSION: ${{ needs.job-initialize.outputs.package_version }}
        permissions:
            contents: read
            packages: write
        steps:

            # #
            #   Release › Checkout
            # #

            - name: '☑️ Checkout'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Initialize › Job Information
            # #

            - name: >-
                  🔄 Load Job
              uses: qoomon/actions--context@v4
              id: 'context'

            # #
            #   Initialize › Start
            # #

            - name: >-
                  ✅ Start
              run: |
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo " Starting Job ${{ steps.context.outputs.job_name }}"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"

                  year="$(date +'%Y')"
                  echo "YEAR=${year}" >> $GITHUB_ENV

                  now="$(date +'%m-%d-%Y %H:%M:%S')"
                  echo "NOW=${now}" >> $GITHUB_ENV

                  now_short="$(date +'%m-%d-%Y')"
                  echo "NOW_SHORT=${now_short}" >> $GITHUB_ENV

                  now_long="$(date +'%m-%d-%Y %H:%M')"
                  echo "NOW_LONG=${now_long}" >> $GITHUB_ENV

                  now_docker="$(date +'%Y%m%d')"
                  echo "NOW_DOCKER=${now_docker}" >> $GITHUB_ENV

                  now_docker_ts="$(date -u +'%FT%T.%3NZ')"
                  echo "NOW_DOCKER_TS=${now_docker}" >> $GITHUB_ENV

                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo -e
                  sudo apt -qq update
                  sudo apt -qq install tree
                  echo -e
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo -e
                  echo " Runner .............. ${{ runner.name }}"
                  echo " Workflow ............ ${{ github.workflow }} (#${{ github.workflow_ref }})"
                  echo " Run Number .......... #${{ github.run_number }}"
                  echo " Ref ................. #${{ github.ref }}"
                  echo " Ref Name ............ #${{ github.ref_name }}"
                  echo " Event Name .......... #${{ github.event_name }}"
                  echo " Repo ................ #${{ github.repository }}"
                  echo " Repo Owner .......... #${{ github.repository_owner }}"
                  echo " Run ID .............. https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  echo " Triggered By ........ ${{ github.actor }}"
                  echo " SHA 1 ............... ${GITHUB_SHA}"
                  echo " SHA 2 ............... ${{ github.sha }}"
                  echo " Workspace ........... ${{ github.workspace }}"
                  echo " PWD ................. ${PWD}"
                  echo " Job Name ............ ${{ steps.context.outputs.job_name }}"
                  echo " Job ID .............. ${{ steps.context.outputs.job_id }}"
                  echo " Job URL ............. ${{ steps.context.outputs.job_url }}"
                  echo " Run ID .............. ${{ steps.context.outputs.run_id }}"
                  echo " Run Attempt ......... ${{ steps.context.outputs.run_attempt }}"
                  echo " Run Number .......... ${{ steps.context.outputs.run_number }}"
                  echo " Run URL ............. ${{ steps.context.outputs.run_url }}"
                  echo " Run Env ............. ${{ steps.context.outputs.environment }}"
                  echo " Run Env URL ......... ${{ steps.context.outputs.environment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Deployment URL .. ${{ steps.context.outputs.deployment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Runner Name ..... ${{ steps.context.outputs.runner_name }}"
                  echo " Run Runner ID ....... ${{ steps.context.outputs.runner_id }}"
                  echo " Year ................ ${YEAR}"
                  echo " Now ................. ${NOW}"
                  echo " Now (Short) ......... ${NOW_SHORT}"
                  echo " Now (Long) .......... ${NOW_LONG}"
                  echo " Now (Docker) ........ ${NOW_DOCKER}"
                  echo " Now (Docker TS) ..... ${NOW_DOCKER_TS}"
                  echo -e
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo -e
                  tree -I node_modules -I .git
                  echo -e
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"

            # #
            #   Windows › Setup NodeJS
            # #

            - name: '⚙️ Setup Node'
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  registry-url: 'https://registry.npmjs.org/'
                  always-auth: true
                  scope: '@aetherinox'

            # #
            #   Windows › Setup Packages
            # #

            - name: '📦 Install NPM & Apt Packages'
              run: |
                  mkdir -p build
                  mkdir -p dist
                  cd ./src
                  sudo apt update
                  sudo apt install git wine64
                  npm install
                  npm install -g electron-packager
                  sudo ln -s /usr/bin/wine /usr/bin/wine64
#              env:
#                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # #
            #   Windows › Verbose › List Tree
            # #

            - name: '🌲 Verbose › Tree Listing'
              run: |
                  tree -I node_modules

            # #
            #   Windows › Build Binary
            # #

            - name: '📦 Build Binaries'
              working-directory: ./src
              run: |
                  npm run build:lin:windows

            # #
            #   Windows › Verbose › List Tree
            # #

            - name: '🌲 Verbose › Tree Listing'
              run: |
                  tree -I node_modules

            # #
            #   Windows › Build › Stable
            # #

            - name: '🔨 Build › Stable › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}.zip'
              id: task_build_st
              if: |
                  startsWith( inputs.RC_RELEASE, false ) ||
                  startsWith( env.RC_RELEASE, false )
              run: |
                  BASE_PATH="${GITHUB_WORKSPACE}"

                  #  windows
                  echo Building STABLE Package ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-arm64.zip
                  (cd build/${{ env.PROJECT_NAME }}-win32-arm64 && zip -r - .) >${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-arm64.zip

                  echo Building STABLE Package ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-ia32.zip
                  (cd build/${{ env.PROJECT_NAME }}-win32-ia32 && zip -r - .) >${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-ia32.zip

                  echo Building STABLE Package ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-amd64.zip
                  (cd build/${{ env.PROJECT_NAME }}-win32-x64 && zip -r - .) >${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-amd64.zip

                  ls

            # #
            #   Windows › Build › Release Candidate
            # #

            - name: '🔨 Build › Release Candidate › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}.zip'
              id: task_build_rc
              if: |
                  startsWith( inputs.RC_RELEASE, true ) ||
                  startsWith( env.RC_RELEASE, true )
              run: |
                  BASE_PATH="${GITHUB_WORKSPACE}"

                  #  windows
                  echo Building RC Package ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-arm64.zip
                  (cd build/${{ env.PROJECT_NAME }}-win32-arm64 && zip -r - .) >${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-arm64.zip

                  echo Building RC Package ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-ia32.zip
                  (cd build/${{ env.PROJECT_NAME }}-win32-ia32 && zip -r - .) >${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-ia32.zip

                  echo Building RC Package ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-amd64.zip
                  (cd build/${{ env.PROJECT_NAME }}-win32-x64 && zip -r - .) >${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-amd64.zip

                  ls

            # #
            #   Windows › Upload Artifacts › Release Files › Stable › Arm64
            # #

            - name: >-
                📋 Upload Artifacts › Stable › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-arm64.zip
              id: task_build_artifact_stable_arm64
              uses: actions/upload-artifact@v4
              if: |
                  startsWith( inputs.RC_RELEASE, false ) ||
                  startsWith( env.RC_RELEASE, false )
              with:
                  name: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-arm64"
                  path: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-arm64.zip"
                  retention-days: 30

            # #
            #   Windows › Upload Artifacts › Release Files › Stable › ia32
            # #

            - name: >-
                📋 Upload Artifacts › Stable › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-ia32.zip
              id: task_build_artifact_stable_ia32
              uses: actions/upload-artifact@v4
              if: |
                  startsWith( inputs.RC_RELEASE, false ) ||
                  startsWith( env.RC_RELEASE, false )
              with:
                  name: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-ia32"
                  path: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-ia32.zip"
                  retention-days: 30

            # #
            #   Windows › Upload Artifacts › Release Files › Stable › amd64
            # #

            - name: >-
                📋 Upload Artifacts › Stable › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-amd64.zip
              id: task_build_artifact_stable_amd64
              uses: actions/upload-artifact@v4
              if: |
                  startsWith( inputs.RC_RELEASE, false ) ||
                  startsWith( env.RC_RELEASE, false )
              with:
                  name: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-amd64"
                  path: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-win32-amd64.zip"
                  retention-days: 30

            # #
            #   Windows › Upload Artifacts › Release Files › Release Candidate › arm64
            # #

            - name: >-
                📋 Upload Artifacts › RC › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-arm64.zip
              id: task_build_artifact_rc_arm64
              uses: actions/upload-artifact@v4
              if: |
                  startsWith( inputs.RC_RELEASE, true ) ||
                  startsWith( env.RC_RELEASE, true )
              with:
                  name: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-arm64"
                  path: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-arm64.zip"
                  retention-days: 30

            # #
            #   Windows › Upload Artifacts › Release Files › Release Candidate › ia32
            # #

            - name: >-
                📋 Upload Artifacts › RC › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-ia32.zip
              id: task_build_artifact_rc_ia32
              uses: actions/upload-artifact@v4
              if: |
                  startsWith( inputs.RC_RELEASE, true ) ||
                  startsWith( env.RC_RELEASE, true )
              with:
                  name: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-ia32"
                  path: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-ia32.zip"
                  retention-days: 30

            # #
            #   Windows › Upload Artifacts › Release Files › Release Candidate › amd64
            # #

            - name: >-
                📋 Upload Artifacts › RC › ${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-amd64.zip
              id: task_build_artifact_rc_amd64
              uses: actions/upload-artifact@v4
              if: |
                  startsWith( inputs.RC_RELEASE, true ) ||
                  startsWith( env.RC_RELEASE, true )
              with:
                  name: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-amd64"
                  path: "${{ env.PROJECT_NAME }}-${{ env.PACKAGE_VERSION }}-rc.${{ inputs.RC_VERSION }}-win32-amd64.zip"
                  retention-days: 30
